#title in header
title: "OlÃ¡, bem vindo"

#main info
#owner
owner: "Leo Omori"
email: leonardoomori@gmail.com
info: "Estudante de ciÃªncias da computaÃ§Ã£o em UTFPR-CM"
#description
desc: "Gosto de escrever cÃ³digo com javascript usando Nodejs e Reactjs ğŸ˜"

#menu
menu:


#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/LeoOmori
linkedin: https://www.linkedin.com/in/leonardo-omori-7a9b10192/



# Misc
nanobar: /js/nanobar.min.js
switch_light: ğŸ¤
switch_dark: ğŸ–¤

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
